### ISSUE TITLE
Facebook sign in not working on iphone 6 (User reported issue)

### ISSUE THREAD

**Issue by nottoast** [CardiffBros/spoons-tracker-web#40]

**Comment by nottoast** [comment]
Has occurred twice for 2 different users

**Comment by mikebroom** [comment]
Worth checking third party cookie settings (as per my issue on Android with Brave browser) and also dependant on browser settings wether pop up blockers are effecting the opening of the Facebook auth window...

**Comment by nottoast** [comment]
Thanks, seems the likely culprit. I've added a warning message to the login screen, I'll commit now and it will be live in a couple of hours
