### ISSUE TITLE
Moderators unable to mark pubs closed if already in Database

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#57]
Simon has said on the group he can only mark pubs he's added as closed, and not ones already in the database..

Would it be possible to raise his privileges (or alternatively lower the restriction on this ) to allow him to do this?

For reference the pub concerned is the Bank House in Cheltenham.

**Comment by nottoast** [comment]
Hi Mike, the reason for this is the majority of pubs (I think around 890) come from the Wetherspoons official website API, so we are really on them to keep the data correct! Another user has raised a few issues on this already. My thought about not letting us edit these would be the next time we update the pubs automatically from the official website, we would blow away any changes simon had made. Lets keep this open for now and we can have a think about how to solve it 

Possibly something to consider when we set up the automatic data refresh from the spoons website (currently has just been done manually once)

**Comment by mikebroom** [comment]
My thoughts are (and I'm not sure how feasible this is) is for any manual fedits to be flagged as "manual edit" or "override" or something... 

Then whenever you do an update from the spoons site (either manually or automatically), then anything with this flag will be backed up (somehow) temporarily- for the update to be done, then once done, be restored back over the imported stuff...

Shouldn't be too many entries, (you would hope)... 

Any entries done manually could have a report an issue option , so if the mods have got it wrong, it could be pointed out easily.

**Comment by nottoast** [comment]
Yeah that all sounds good. That's roughly how the user admin pubs are added at the moment, so it shouldn't be too much of a stretch to allow the editing of wetherspoons API provided pubs!

One thing we need to think about is how the admin section will look after allowing to select all types of pubs, the current setup won't suffice I don't think.. so that may need a re-design.

Let me know if you want me to you an admin so you can take a look

**Comment by mikebroom** [comment]
Would love to have a look if at all possible? Will provide thoughts and feedback as always. 
Thanks 😀

**Comment by mikebroom** [comment]
Found the admin page at 23:40 and was able to access it? Guessing this is prior to being added as an admin?  Presume authorisation needed (or is broken?)

**Comment by nottoast** [comment]
Thanks, good spot! I'll make you an admin now so if you do want to edit in the future you can. I'll have a look into this as a separate issue

**Comment by nottoast** [comment]
This has been added and committed
