### ISSUE TITLE
Add a report an issue button/menu

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#61]
For instance

Report pub closed (permanent/refurb ) (hopefully would be picked up on group mind)
Wrong address
Wrong Map location

**Comment by nottoast** [comment]
This is a good idea for when we go live, there's quite a large number of people which could potentially be using the site, so we need to have a way of collecting and organizing all the support issues. I'll probably make a new email account for this

**Comment by nottoast** [comment]
Added and committed, just kept it short and simple as a gmail email address for the time being, can possibly look at something more advanced if we find that unmanageable
