### ISSUE TITLE
Rate a pub feature

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#63]
When logging a visit maybe give a star rating? Find out the most liked/loathed pubs? 
E.g. 4.7 rating from 1000 logged visits..

Could go down to reviewing level but not sure if that could be awkward ground with comments that may not go down too well.. personal I think. A simple star rating would be nice..

**Comment by nottoast** [comment]
Good idea, I'd like this as an option in the pub details area of the site, probably more of a v2 feature though along with the other ideas mentioned (is pub temp closed, address, pictures etc)

**Comment by nottoast** [comment]
This is 90% done, small bug to work on at the moment but looking at releasing tomorrow

**Comment by nottoast** [comment]
This has been added, committing and deploying - Currently works by a thumbs up / down system - if 9 people thumb up and 1 thumbs down, the pub gets a 4.5 rating
