### ISSUE TITLE
Import Foursquare/Swarm checkins

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#65]
I've used foursquare for just over 7 years and they have all the spoons listed, and keep your check in history even if a venue closed... not sure if any others use it, or if the work is feasible for the results it'll give.. it does have a full api for access to the data there...,

**Comment by nottoast** [comment]
Interesting idea, would be good to see if many people use these services? If they do then maybe we could have a look at adding some kind of integration in a future release. I'll probably put this on the backlog for now until we have a more firm view of numbers

**Comment by mikebroom** [comment]
My poll on the group regarding this so far doesn't seem that promising...  I'll leave it open for a while longer but majority seem happy with Facebook places ... Looks again like I'm one of the minority geeks lol.

**Comment by mikebroom** [comment]
With 66 responses showing use of Facebook places and just 4 for Foursquare on the poll on the group I'd say this is probably dead before it's started. Would see too little use to be worthwhile.
