### ISSUE TITLE
Non admin able to access admin page.

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#69]
Non admin users are able to access admin page (although unable to commit changes to database)

Ideally should return a not accessible page

**Comment by nottoast** [comment]
Fixed this issue and committed

**Comment by mikebroom** [comment]
Still visible and accessible by non admin account?
![img_1662](https://cloud.githubusercontent.com/assets/28717957/26278680/44c18088-3d98-11e7-9b93-ccaf30f14263.PNG)

**Comment by nottoast** [comment]
Yeah I thought I'd fixed this but had to take the change out as it wasn't working as I'd hoped, I'll reopen and have another look

**Comment by nottoast** [comment]
Fixed this issue again, hope it works this time!
