### ISSUE TITLE
Admin Search option

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#73]
The pull down menu option is pretty inefficient/awkward if searching for a pub to edit and it's not listed near the top. Would it be possible to have a search option (as when marking pubs off as a standard user).

**Comment by mikebroom** [comment]
Alternatively,  have an edit button next to the tick button in the normal pub search list for those with admin privileges? Depends if it slows down the search or adds too much clutter..

**Comment by nottoast** [comment]
Yeah that's a good idea! I was thinking along similar lines, I think this would be a nice neat solution, and also we only have to code up a single pub list / search function.. will be looking into this soon

**Comment by nottoast** [comment]
This has been added with the new admin enhancement, so closing for now
