### ISSUE TITLE
Symbols - Quick reference on main page

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#79]
Would it be possible to have a quick reference to the symbols on the main page?
Roadworks - Closed for refurbishment
Red Cross - Closed Spooons 
Greeen pin - visited spoons
Blue pin - required spoons
I think that's it unless you can think of anything else?

Nothing extravagant, but would be nice for new users to see and would avoid them saying "but I went all this way to visit as it was on the map"...

Obvious if it expands over time, maybe move to a separate page (if the home page ends up cluttered).

**Comment by nottoast** [comment]
Good idea! Hadn't thought of that. I've added it in 👍 

It doesn't look too bad at the moment as its only 4 icons, but if we add others might need to make a new page as you say
