### ISSUE TITLE
Remove Closed Pubs from Map

### ISSUE THREAD

**Issue by mikebroom** [CardiffBros/spoons-tracker-web#80]
Having had a chat with Simon, we're both of the opinion that the closed pubs should (if possible) be removed from the map. At least for the initial release, untill a toggle setup (filtering open/closed/visited/not visited) can be implemented in future releases.

Neither of us can see the logic of having them on the map - but obviously they still need to be in the tick list..

Any chance of tweaking this before release?

**Comment by nottoast** [comment]
Hi Mike, good idea.. agree with that completely. This should be quite trivial, I'll have a look later or tomorrow

**Comment by nottoast** [comment]
This has been fixed and committed, I'll probably deploy to live tomorrow evening
